train:

  - name: "1.pickup"
    task_kinds: pickup

  # CLEAN tasks
  - name: "2.a.clean"
    task_kinds: clean

  - name: "3.place_cleaned"
    task_kinds: place_cleaned

  # SLICE tasks
  - name: "2.a.slice"
    task_kinds: slice
    taskarg_options:
      x: food1

  - name: "3.place_sliced"
    task_kinds: place_sliced
    taskarg_options:
      x: food1

  - name: "5.cook_sliced"
    task_kinds: cook_sliced
    taskarg_options:
      x: food1

  # COOK tasks
  - name: "3.cook"
    task_kinds: cook
    taskarg_options:
      x: food2 

  - name: "4.place_cooked"
    task_kinds: place_cooked
    taskarg_options:
      x: food2

  - name: "5.cook_with_cleaned"
    task_kinds: cook_with_cleaned
    taskarg_options:
      x: food2


test:

  - name: "1.pickup"
    task_kinds: pickup

  # CLEAN tasks
  - name: "2.a.clean"
    task_kinds: clean

  - name: "3.place_cleaned"
    task_kinds: place_cleaned

  # SLICE tasks
  - name: "2.a.slice"
    task_kinds: slice
    taskarg_options:
      x: food2

  - name: "3.place_sliced"
    task_kinds: place_sliced
    taskarg_options:
      x: food2

  - name: "5.cook_sliced"
    task_kinds: cook_sliced
    taskarg_options:
      x: food2

  # COOK tasks
  - name: "3.cook"
    task_kinds: cook
    taskarg_options:
      x: food1

  - name: "4.place_cooked"
    task_kinds: place_cooked
    taskarg_options:
      x: food1

  - name: "5.cook_with_cleaned"
    task_kinds: cook_with_cleaned
    taskarg_options:
      x: food1