train:

  - name: pickup
    task_kinds: pickup

  - name: place_on_y
    task_kinds: place
    num_dists: 1
    taskarg_options:
      x: lettuce
      y: can_contain

  - name: place_x
    task_kinds: place
    num_dists: 1
    taskarg_options:
      x: food
      y: fridge

test:
  - name: place_on_y_test  # all except lettuce
    task_kinds: place
    num_dists: 1
    taskarg_options:
      x: [tomato, onion, potato, apple, orange]
      y: can_contain

  - name: place_x_test # all except fridge
    task_kinds: place
    num_dists: 1
    taskarg_options:
      x: food
      y: [sink, pot, pan, plates, bowl]


valid_actions: [left, right, forward, pickup_contents, place]