train:

  - name: pickup_nodist
    task_kinds: pickup
    num_dists: 0

  - name: pickup
    task_kinds: pickup
    num_dists: 2

  - name: place_on_y_nodist
    task_kinds: place
    num_dists: 0
    taskarg_options:
      x: [tomato, onion, potato]
      y: can_contain

  - name: place_x_nodist
    task_kinds: place
    num_dists: 0
    taskarg_options:
      x: food
      y: [sink, pot, pan]

  - name: place_on_y
    task_kinds: place
    num_dists: 2
    taskarg_options:
      x: [tomato, onion, potato]
      y: can_contain

  - name: place_x
    task_kinds: place
    num_dists: 2
    taskarg_options:
      x: food
      y: [sink, pot, pan]

test:
  - name: place_on_y_test  # all except lettuce
    task_kinds: place
    num_dists: 2
    taskarg_options:
      x: [lettuce, apple, orange]
      y: can_contain

  - name: place_x_test # all except fridge
    task_kinds: place
    num_dists: 2
    taskarg_options:
      x: food
      y: [fridge, plates, bowl]


valid_actions: [left, right, forward, pickup_contents, place]