# Copyright 2018 DeepMind Technologies Limited. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""FactoredMuZero Builder.

Changes from MuZero:
- builder accepts networks factory as input.
  This is used to create dummy parameters for making a dummy actor_state.
  The assumption of this class is that the intial_state function for the RNN requires parameters.
  This is used in (1) make_replay_tables & (2) make_adder

"""
from typing import Generic, Iterator, List, Optional

import acme
from acme import adders
from acme import core
from acme import specs
from acme.adders.reverb import structured
from acme.adders import reverb as adders_reverb
from acme.adders.reverb import base as reverb_base
from acme.adders.reverb import structured
from acme.agents.jax import actor_core as actor_core_lib
from acme.agents.jax import actors
from acme.agents.jax import builders
from acme.agents.jax.r2d2 import config as r2d2_config
from acme.agents.jax.r2d2 import learning as r2d2_learning
from acme.agents.jax.r2d2 import networks as r2d2_networks
from acme.datasets import reverb as datasets
from acme.jax import networks as networks_lib
from acme.jax import utils
from acme.jax import variable_utils
from acme.utils import counting
from acme.utils import loggers
import jax
import optax
import reverb
from reverb import structured_writer as sw
import tensorflow as tf
import tree

from reverb import structured_writer as sw

from acme.agents.jax import r2d2

from muzero.learning import MuZeroLearner
from muzero import actor as muzero_actor
from muzero.ve_losses import ValueEquivalentLoss
from muzero import learner_logger
from muzero.builder import MuZeroBuilder

class FactoredMuZeroBuilder(MuZeroBuilder):
  """MuZero Builder.

  This constructs all the pieces of MuZero.
  """

  def __init__(
          self,
          network_factory = None,
          **kwargs):
    """Creates a R2D2 learner, a behavior policy and an eval actor."""
    super().__init__(**kwargs)
    self._network_factory = network_factory

  def make_replay_tables(
      self,
      environment_spec: specs.EnvironmentSpec,
      policy: muzero_actor.R2D2Policy,
  ) -> List[reverb.Table]:
    """Create tables to insert data into."""
    # HACK to get parameters as input for initialization.
    dummy_key = jax.random.PRNGKey(0)
    dummy_networks = self._network_factory(environment_spec)
    dummy_params = dummy_networks.unroll_init(dummy_key)
    dummy_actor_state = policy.init(dummy_key, dummy_params)
    del dummy_params
    del dummy_networks
    # end hack

    extras_spec = policy.get_extras(dummy_actor_state)
    step_spec = structured.create_step_spec(
        environment_spec=environment_spec, extras_spec=extras_spec)
    if self._config.samples_per_insert:
      samples_per_insert_tolerance = (
          self._config.samples_per_insert_tolerance_rate *
          self._config.samples_per_insert)
      error_buffer = self._config.min_replay_size * samples_per_insert_tolerance
      limiter = reverb.rate_limiters.SampleToInsertRatio(
          min_size_to_sample=self._config.min_replay_size,
          samples_per_insert=self._config.samples_per_insert,
          error_buffer=error_buffer)
    else:
      limiter = reverb.rate_limiters.MinSize(self._config.min_replay_size)
    return [
        reverb.Table(
            name=self._config.replay_table_name,
            sampler=reverb.selectors.Prioritized(
                self._config.priority_exponent),
            remover=reverb.selectors.Fifo(),
            max_size=self._config.max_replay_size,
            rate_limiter=limiter,
            signature=sw.infer_signature(
                configs=r2d2.builder._make_adder_config(
                    step_spec, self._sequence_length,
                    self._config.sequence_period),
                step_spec=step_spec))
    ]

  def make_adder(
          self, replay_client: reverb.Client,
          environment_spec: Optional[specs.EnvironmentSpec],
          policy: Optional[muzero_actor.R2D2Policy]) -> Optional[adders.Adder]:
    """Create an adder which records data generated by the actor/environment."""
    if environment_spec is None or policy is None:
      raise ValueError('`environment_spec` and `policy` cannot be None.')
    # HACK to get parameters as input for initialization.
    dummy_key = jax.random.PRNGKey(0)
    dummy_networks = self._network_factory(environment_spec)
    dummy_params = dummy_networks.unroll_init(dummy_key)
    dummy_actor_state = policy.init(dummy_key, dummy_params)
    del dummy_params
    del dummy_networks
    # end hack

    extras_spec = policy.get_extras(dummy_actor_state)
    step_spec = structured.create_step_spec(
        environment_spec=environment_spec, extras_spec=extras_spec)
    return structured.StructuredAdder(
        client=replay_client,
        max_in_flight_items=5,
        configs=r2d2.builder._make_adder_config(step_spec, self._sequence_length,
                                   self._config.sequence_period),
        step_spec=step_spec)
