train:


  - name: "1.pickup"
    task_kinds: pickup
    num_dists: 0

  - name: "2.a.slice"
    task_kinds: slice
    num_dists: 0

  - name: "2.a.clean"
    task_kinds: clean
    num_dists: 0

  - name: "2.b.pickup_cleaned"
    task_kinds: pickup_cleaned
    num_dists: 0

  - name: "2.b.pickup_sliced"
    task_kinds: pickup_sliced
    num_dists: 0

  - name: "3.cook"
    task_kinds: cook
    num_dists: 0

  - name: "3.place_sliced"
    task_kinds: place_sliced
    num_dists: 0

  - name: "3.place_cleaned"
    task_kinds: place_cleaned
    num_dists: 0

  - name: "4.place_cooked"
    task_kinds: place_cooked
    num_dists: 0

  - name: "5.cook_with_cleaned"
    task_kinds: cook_with_cleaned
    num_dists: 0

  - name: "5.cook_sliced"
    task_kinds: cook_sliced
    num_dists: 0