test:

  - name: place_sliced_test_dist2
    task_kinds: place2_sliced
    taskarg_options:
      x: food
    num_dists: 2

  - name: place_sliced_test_dist5
    task_kinds: place2_sliced
    taskarg_options:
      x: food
    num_dists: 5

  - name: place_sliced_test_dist8
    task_kinds: place2_sliced
    taskarg_options:
      x: food
    num_dists: 8

train:

  # Pickup Sliced
  - name: pickup_sliced_train_dist2
    task_kinds: pickup_sliced
    taskarg_options:
      x: food
    num_dists: 2

  - name: pickup_sliced_train_dist0
    task_kinds: pickup_sliced
    taskarg_options:
      x: food
    num_dists: 0

  # Place Chilled
  - name: place_chilled_train_dist2
    task_kinds: place2_chilled
    taskarg_options:
      x: food
    num_dists: 2

  - name: place_chilled_train_dist0
    task_kinds: place2_chilled
    taskarg_options:
      x: food
    num_dists: 0

  # Place Cleaned
  - name: place_cleaned_train_dist2
    task_kinds: place2_cleaned
    taskarg_options:
      x: [container, utensil]
    num_dists: 2

  - name: place_cleaned_train_dist0
    task_kinds: place2_cleaned
    taskarg_options:
      x: [container, utensil]
    num_dists: 0


  # Pickup {Food, Utensil, Container}
  - name: pickup_train_dist0
    task_kinds: pickup
    taskarg_options:
      x: [food, utensil, container]
    num_dists: 0

  - name: pickup_train_dist2
    task_kinds: pickup
    taskarg_options:
      x: [food, utensil, container]
    num_dists: 2

